import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "./components";
import StoreProvider from "./providers/StoreProvider";
import { AuthProvider } from "./providers/AuthProvider";
import { Toaster } from "react-hot-toast"; // ✅ Importar Toaster

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "600", "700", "900"],
	variable: "--font-poppins",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.variable}>
				<StoreProvider>
					<AuthProvider>
						<LayoutWrapper>
							{children}
							<Toaster position="top-left" toastOptions={{ duration: 3000 }} /> 
						</LayoutWrapper>
					</AuthProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
