import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "./_components";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "600", "700", "900"], // Escoge los pesos que necesites
	variable: "--font-poppins",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<LayoutWrapper>
			<html lang="en">
				<body className={poppins.variable}>{children}</body>
			</html>
		</LayoutWrapper>
	);
}
